{
 "title": "HTTP Auth API",
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "endpoint" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests per 20s - auth_login",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(http_auth_login_statuses[20s])",
     "legendFormat": "{{status_code}} - Requests per 20s"
    }
   ]
  },
  {
   "title": "HTTP Requests per 20s - auth_logout",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(http_auth_logout_statuses[20s])",
     "legendFormat": "{{status_code}} - Requests per 20s"
    }
   ]
  },
  {
   "title": "HTTP Requests per 20s - auth_me",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(http_auth_me_statuses[20s])",
     "legendFormat": "{{status_code}} - Requests per 20s"
    }
   ]
  },
  {
   "title": "HTTP Requests per 20s - auth_register_by_login",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(http_auth_register_by_login_statuses[20s])",
     "legendFormat": "{{status_code}} - Requests per 20s"
    }
   ]
  },
  {
   "title": "Request Duration (95th Percentile) - auth_register_by_login",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_auth_register_by_login_duration_seconds_bucket[20s]))",
     "legendFormat": "95th Percentile Duration"
    }
   ]
  },
  {
   "title": "Request Duration (95th Percentile) - login",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_auth_login_duration_seconds_bucket[20s]))",
     "legendFormat": "95th Percentile Duration"
    }
   ]
  },
  {
   "title": "Request Duration (95th Percentile) - logout",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_auth_logout_duration_seconds_bucket[20s]))",
     "legendFormat": "95th Percentile Duration"
    }
   ]
  },
  {
   "title": "Request Duration (95th Percentile) - me",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_auth_me_duration_seconds_bucket[20s]))",
     "legendFormat": "95th Percentile Duration"
    }
   ]
  }
 ]
}